spring.application.name=middle-service
server.port=8081

# Configuration du service SOAP à consommer
soap.service.url=http://localhost:8085/ws
soap.service.wsdl=http://localhost:8085/ws/servers.wsdl

# Springdoc OpenAPI (Swagger)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

